=== gedex/simflow/lib/config-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"url": {
			"type": "string",
			"format": "uri"
		},
		"users": {
			"type": "object",
			"patternProperties": {
				"^[a-zA-Z0-9_]+$": {
					"$ref": "#user"
				}
			},
			"minProperties": 1
		},
		"frames": {
			"type": "object",
			"patternProperties": {
				"^[a-zA-Z0-9_]+$": { "type": "string" }
			},
			"minProperties": 1
		},
		"selectors": {
			"type": "object",
			"patternProperties": {
				"^[a-zA-Z0-9_]+$": {
					"anyOf": [
						{
							"type": "string"
						},
						{
							"type": "object",
							"properties": {
								"str": {
									"type": "string"
								},
								"type": {
									"type": "string",
									"enum": [ "css", "xpath" ]
								}
							},
							"required": [ "selector", "type" ]
						}
					]
				}
			},
			"minProperties": 1
		},
		"initialState": { "type": "string" },
		"flows": {
			"type": "object",
			"patternProperties": {
				"^[a-zA-Z0-9_]+$": {
					"$ref": "#flow"
				}
			},
			"minProperties": 1
		}
	},
	"required": [ "url", "initialState", "flows" ],
	"definitions": {
		"user": {
			"$id": "#user",
			"type": "object",
			"properties": {
				"username": { "type": "string" },
				"password": { "type": "string" }
			},
			"required": [ "username", "password" ]
		},
		"flow": {
			"$id": "#flow",
			"type": "object",
			"properties": {
				"requireUser": {
					"anyOf": [ { "type": "boolean" }, { "type": "string" } ]
				},
				"inputState": { "type": "string" },
				"steps": {
					"type": "array",
					"items": {
						"type": "string"
					},
					"minItems": 1
				},
				"outputState": { "type": "string" }
			},
			"required": [ "inputState", "steps", "outputState" ]
		}
	}
}

=== gedex/simflow/lib/config-default.json
{
	"url": "https://example.com",
	"users": {
		"customer": {
			"username": "",
			"password": ""
		},
		"admin": {
			"username": "",
			"password": ""
		}
	},
	"selectors": {
		"loginLink": "#login-link",
		"logoutLink": "#logout-link",
		"usernameField": "#username",
		"passwordField": "#password",
		"loginButton": "#login-button"
	},
	"initialState": "notLoggedIn",
	"flows": {
		"login": {
			"requireUser": true,
			"inputState": "notLoggedIn",
			"steps": [
				"Goto /",
				"See loginLink",
				"Click loginLink",
				"Page reloads",
				"See usernameField",
				"Type in usernameField user.username",
				"See usernameField",
				"Type in usernameField user.username"
			],
			"outputState": "loggedIn"
		},
		"logout": {
			"inputState": "loggedIn",
			"steps": [
				"goto page /my-dashboard",
				"see logoutLink",
				"click logoutLink",
				"see loginLink"
			],
			"outputState": "notLoggedIn"
		}
	}
}
